version: "3.8"

services:
  postgresdb:
    container_name: postgresdb
    image: 'postgres:13.1-alpine'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=courses
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres
volumes:
  db: