spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/courses
    username: postgres
    password: admin
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update